version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GEMINI_API_TOKEN=your_gemini_api_token
    volumes:
      - .:/app
    stdin_open: true # Keep container running
    tty: true
